name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil source code dari repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build & Push Backend (Server)
      - name: Build and push Server image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: engineerman007/perpustakaan-server:latest

      # 4. Build & Push Frontend (Client)
      - name: Build and push Client image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: engineerman007/perpustakaan-client:latest
